### ISSUE TITLE
Singleton mixin must not have the empty default constructor

### ISSUE THREAD

**Issue by Zardoz89** [mw66/jdiutil#1]
The Singleton mixin must not have the empty default constructor.

- First, don't work as a library, because needs the context. 

Perhaps could work if the jdiutil targetType is set to "sourceLibrary".

If you append it to another project, and try this example code with "dub test" :
```D
;
import std.experimental.logger;

import jdiutil;

@("jdiutil")
unittest
{
    class Point
    {
        // declare fields
        mixin ReadOnly! (int,     "x", 3);
        mixin ReadWrite!(double,  "y");
        mixin ReadWrite!(string,  "label", "default value");

        // atomic counter
        mixin AtomicCounted;
        // this is a Singleton class!
        mixin Singleton!Point;
        
        // debug print string helper
        mixin ToString!Point;

    }

    int i = 100;
    double d = 1.23456789;
    Point thePoint = Point.getSingleton();

    // multiple vars separated by ';'
    // _S with var name; _s without var name
    writeln(mixin(_S!"print with    var name: {i; d; thePoint}"));
    writeln(mixin(_s!"print without var name: {i; d; thePoint}"));

    //thePoint.x = 4;  // compile Error: x is ReadOnly
    thePoint.y = 4;  // ok
    thePoint.incCount();
    log.info(mixin(_S!"works in logger too: {i; d; thePoint}"));

    thePoint.y(3.14).label("pi");  // ok
    string str = mixin(_S!"assign to string with custom format: {i; d%06.2f; thePoint}");
    writeln(str);

    Point samePoint = Point.getSingleton();
    samePoint.incCount();
    writeln(mixin(_S!"it's the same point: {thePoint; samePoint}"));
}
```

Fails with this error :
```
../../../.dub/packages/jdiutil-1.0.2/jdiutil/source/jdiutil.d(200,33): Error: outer function context of ddiv.core.jdiutil_spec.__unittest_L11_C1 is needed to new nested class ddiv.core.jdiutil_spec.__unittest_L11_C1.Point
/usr/include/dmd/phobos/std/experimental/logger/core.d(956,33): Error: template std.experimental.logger.core.formatString cannot deduce function from argument types !()(MsgRange, void, string), candidates are:
/usr/include/dmd/phobos/std/experimental/logger/core.d(658,14):        formatString(A...)(MsgRange oRange, A args)
/usr/include/dmd/phobos/std/experimental/logger/core.d(484,44): Error: template instance std.experimental.logger.core.Logger.memLogFunctions!cast(LogLevel)cast(ubyte)64u.logImpl!(42, "tests/ddiv/core/jdiutil_spec.d", "ddiv.core.jdiutil_spec.__unittest_L11_C1", "void ddiv.core.jdiutil_spec.__unittest_L11_C1()", "ddiv.core.jdiutil_spec", void, string) error instantiating
tests/ddiv/core/jdiutil_spec.d(42,13):        instantiated from here: defaultLogFunction!(42, "tests/ddiv/core/jdiutil_spec.d", "ddiv.core.jdiutil_spec.__unittest_L11_C1", "void ddiv.core.jdiutil_spec.__unittest_L11_C1()", "ddiv.core.jdiutil_spec", void, string)
/usr/bin/dmd failed with exit code 1.
```

- Second, if the user of jdiutil needs to do stuff on the class/struct constructor, he can't

- Third, can't work with structs.
Structs don't have default constructor method, however, can be disabled with @disabled this() {}

**Comment by mw66** [comment]
You question can be answered by a google search "Why is it mandatory to have private Constructor inside a Singleton class", e.g.

https://stackoverflow.com/questions/9963667/why-is-it-mandatory-to-have-private-constructor-inside-a-singleton-class

https://en.wikipedia.org/wiki/Singleton_pattern

Also, the purpose of Singleton pattern is to prevent user from construct multiple objects other than using getSingleton() method; without define private default constructor, if the user inherit from the Singleton class, then the user can construct multiple objects of the derived class, this defeat the purpose of Singleton pattern.

To use any design pattern, the user have to adhere to the rules of that pattern.

Regarding to your problem:
1. can be solved by add static: "static class Point {...}"
2. you need add another method, e.g. doOtherInitStuff(); and after get the single instance, call it:
```
Point thePoint = Point.getSingleton();
thePoint.doOtherInitStuff();
```
3. Singleton pattern is intended to be only applied to class. Since most of the time, people use struct as stack variable, and may define multiple of them (otherwise, user have to user struct* to pointing to the same object).  For singleton object on the heap, why not just use class?

I added compile time error message here:

https://github.com/mingwugmail/jdiutil/blob/master/source/jdiutil.d#L187

**Comment by mw66** [comment]
Just want to add: since the constructor has to be hided in the Singleton template, and the template knows nothing about the user's intent, the safest bet is to add empty default constructor body.

**Comment by Zardoz89** [comment]
I know very well the Singleton pattern. My self, I wrote a mixin that does something similar that you (plus I implemented singletons on Java and C++) . What I means, is that the **user of the jdiutil MUST implement the private constructor itself**. 

Indeed, for structs not make sense. Forgot that.

**Comment by mw66** [comment]
> user of the jdiutil MUST implement the private constructor itself.

Hmm, I will add an extra param to the template parameter (default to empty body) to allow user pass in his own initFun(). 

Later then.  Or if you have time, send a PR :-)

**Comment by mw66** [comment]
@Zardoz89 after careful thought, I decided not to introduce another template parameter, which will make the things complicated, instead I added a customInit(...) demo in the example:

https://github.com/mingwugmail/jdiutil/blob/master/source/app.d#L24
```
  // the Singleton only has empty {} ctor, customInit(...) can be done like this
  Point customInit(double whatever) {
    _y = whatever;
    return this;
  }
```

and call it like this:

https://github.com/mingwugmail/jdiutil/blob/master/source/app.d#L40
```
        Point thePoint = Point.getSingleton().customInit(0.456);  // customInit(...)!
```

still an one-liner; in contrast, if we do it like this:
```
        auto thePoint = Point!(customInit, 0.456).getSingleton();
```
will 
1. complicate the code (read hard to maintain)
2. same one-liner, less readable.

I don't think it makes sense.
